{% set name = "flytekitplugins-dask" %}
{% set version = "1.12.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7ddbf4ec805b9f096f4c48d68d05321f3aa81c3012975598d846ae224d80880d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - flyteidl >=1.3.2
    - flytekit >=1.3.0,<2.0.0
    - dask-core >=2022.10.2

test:
  imports:
    - flytekitplugins.dask
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/flyteorg/flytekit/tree/master/plugins/flytekit-dask
  summary: Dask plugin for flytekit
  license: Apache-2.0
  license_file: LICENSE
  description: |
    Plugin to manage Dask workloads within Flyte. 

    - Flyte HomePage: https://flyte.org
    - Flyte Docs: http://docs.flyte.org/

    PyPI: [https://pypi.org/project/flytekitplugins-dask/](https://pypi.org/project/flytekitplugins-dask/)

  doc_url: https://flytecookbook.readthedocs.io/en/latest/
  dev_url: https://github.com/flyteorg/flytekit

extra:
  recipe-maintainers:
    - bstadlbauer
    - cosmicBboy
